### ISSUE TITLE
Vmware installer  

### ISSUE THREAD

**Issue by outlaw12321** [weaknetlabs/Demon-Linux-Installer#2]
Idk if I'm in the right section but far as what I've read you can only install demon os to a virtual box correct.  I have got it to boot and run on both my lenovo flex 4 and my yoga 940 custom from a usb but having a issue with no wifi.  My blue wave n9000 and my apfa doesnt pick up anything. Tired airmon wifigtk  rfkill nothing is blocked is this a result of it just the config or is it just not going to work installing it to usb with persistence

**Comment by RackunSec** [comment]
Hello. This is for tracking issue with the installer itself. I placed a message within the installer (at tyhe very end) to email me directly with OS issues. I am not familiar with "apfa" or "bluewave n9000" so, you may have to search Google on how to install drivers for those using Debian Linux.

**Comment by outlaw12321** [comment]
My issue was more a question as  in can you install demon os to you're ssd
permanently and. Not have to use on vmware.
