### ISSUE TITLE
Main OS

### ISSUE THREAD

**Issue by midusgrey** [weaknetlabs/Demon-Linux-Installer#3]
Hello there.. Can I install it to be the main OS not on a virtual machine?

**Comment by RackunSec** [comment]
Hello. 
As long as the gParted application can see your disk, then yes. The installer installs the OS files using rsync and updates package repositories. Finally it installs the Linux kernel (OS) and the GRUB boot-loader to your disk. As long as your boot loader can see your disk at start up, it should work just fine. Virtualization is not unlike the boot process from a machine. The machine is simply virtualized.
